FROM alpine:latest

# Installa le dipendenze
RUN apk add --update gcc g++ clang gdb cmake make ninja autoconf automake dos2unix tar rsync hiredis hiredis-dev libpq-dev nlohmann-json valgrind git redis curl-dev boost-dev\
    && rm -rf /tmp/* /var/cache/apk/*

# Crea una directory per il progetto
WORKDIR /app

RUN mkdir -p /src

COPY . .

# Crea una build directory e compila il progetto
RUN cd ./src/control_center && g++ -o test main.cpp -lpq -lhiredis

# Comando per eseguire il server
CMD ["./src/control_center/test"]